### ISSUE TITLE
Numpy ImportError in train.py

### ISSUE THREAD

**Issue by se4u** [kiryor/NNPUlearning#2]
It seems that the last commit to move from surrogate loss to 0-1 loss broke train.py.

https://github.com/kiryor/nnPUlearning/blob/fe443ef1b407f2a6ae9eece75cde922eb001855c/train.py#L196

To reproduce the NIPS results can we just use the commit from April last year, `fix bug of CIFAR10 (baef0a3)`, instead ?

**Comment by se4u** [comment]
Another error is in the increment operations in `train.py`

https://github.com/kiryor/nnPUlearning/blob/fe443ef1b407f2a6ae9eece75cde922eb001855c/train.py#L202
https://github.com/kiryor/nnPUlearning/blob/fe443ef1b407f2a6ae9eece75cde922eb001855c/train.py#L206
https://github.com/kiryor/nnPUlearning/blob/fe443ef1b407f2a6ae9eece75cde922eb001855c/train.py#L210

The output of `compute_prediction_summary` is a tuple of array which needs to be converted to a numpy array as follows

```python
def arrify(tpl):                               
    return np.array([float(e) for e in tpl])   

....

summary[k] += arrify(target.compute_prediction_summary(*in_vars))
```

**Comment by se4u** [comment]
Finally even after all of these changes, by looking at the `training_error.png` we can see that the 0-1 loss for the training data is not being correctly calculated. For example see

https://github.com/se4u/nnPUlearning/tree/k20gpu
https://github.com/se4u/nnPUlearning

The test error logs are fine, but the training error logs are very strange. I could look into it, but it may be much easier for the original authors of the code to figure out the right fix.

**Comment by YusukeO** [comment]
same here.

**Comment by caomxin** [comment]
same here. Needs further clarification.

**Comment by ricardocarvalhods** [comment]
Same here.

**Comment by kiryor** [comment]
Thanks for bringing this up. This issue was due to my misconfiguration of numpy in `train.py` and the incompatibility of cupy version.
I fixed the issue by casting returned variables in `compute_prediction_summary` to int.
