### ISSUE TITLE
Where are the fitted model stored and how to use it?

### ISSUE THREAD

**Issue by s1sun** [kiryor/NNPUlearning#4]
Could you please give more detailed codes for below tasks after execution of train.py? 
1) where and how to load the fitted model.
2) how to use it with new data for prediction.
3) output files for result of the prediction.
Thanks

**Comment by kiryor** [comment]
Please read chainer official document.
1. You can save the trained model by adding `chainer.training.extensions.snapshot` to the trainer using trainer.extend method.
2.  For our model classes, MyClassifier.calculate(x) returns the raw output of the prediction result. You can aggregate or arrange as you want.
3. I don't know chainer has such a feature. You can use native python by getting the raw output.

**Comment by s1sun** [comment]
Thanks for reply.
Best regards,
sean

________________________________
