### ISSUE TITLE
Request: Release the code in this repository under some open source license

### ISSUE THREAD

**Issue by shaypal5** [kiryor/NNPUlearning#7]
Hey @kiryor, :)

First, kudos and thank you for your very cool research paper on Positive-Unlabeled Learning with Non-Negative Risk Estimator, and this accompanying implementation.

Second, I was wondering: Would you be willing to release the code in this repository under some open source license (may I suggest MIT or BSD 3-clause)?

It would enable people to use it in open source projects (which is what I hope to do).

As you perhaps know, as long as you do not explicitly release code under an open source license the rights are implicitly reserved to the writer (in this case, obviously, just for the implementation, not the algorithm) without permitting any kind of use.

Releasing it explicitly, however, you may reserve rights to it while explicitly allowing almost all kinds of use with it, but releasing yourself from any warranty or liability.

If I've convinced you, then it's as easy as creating a LICENSE file and pasting the short text of the license inside, putting in your name and the year:
* MIT: https://choosealicense.com/licenses/mit/
* BSD 3-clause: https://opensource.org/licenses/BSD-3-Clause

Cheers,
Shay

**Comment by kiryor** [comment]
Hi Shay,

Thank you for getting interested in our work and our code. We are happy to grant MIT license to this repository.

Thanks,
Ryuichi

**Comment by shaypal5** [comment]
Hi Ryuichi! :)

Thank you very much for this contribution to open source and the public domain.

Cheers,
Shay
